LogLevel warn rewrite:trace3

<VirtualHost *:80>
    ServerName www.local
    DocumentRoot "/srv/www.local"

    <Directory "/srv/www.local">
        Require all granted
        AllowOverride None
    </Directory>

    <FilesMatch "\.php$">
        SetHandler "proxy:fcgi://php:9000"
    </FilesMatch>
</VirtualHost>

<VirtualHost *:80>
    ServerName static.local
    DocumentRoot "/srv/static.local"

    <Directory "/srv/static.local">
        Require all granted
        AllowOverride None
    </Directory>

    <Directory "/srv/www.local">
        Require all granted
    </Directory>

    RewriteEngine On
    RewriteRule "^/html/(.*)$" "/$1.html" [L]
</VirtualHost>