FROM httpd:2.4.59-bookworm

RUN sed -i 's/^#LoadModule rewrite_module/LoadModule rewrite_module/' /usr/local/apache2/conf/httpd.conf \
 && printf '\nAllowEncodedSlashes On\nInclude conf/extra/path-truncation.conf\n' >> /usr/local/apache2/conf/httpd.conf

COPY conf/path-truncation.conf /usr/local/apache2/conf/extra/path-truncation.conf